version: 0.0
os: ubuntu
files:
  - source: /manage.py
    destination: /var/manage.py
hooks:
  BeforeInstall:
    - location: django
      command: pip install -r requirements.txt
      runas: root
  AftereInstall:
    - location: django/notejam
      command: ./manage.py syncdb
      command: ./manage.py migrate
      command: ./manage.py runserver 0:8000
      runas: root
   

